### ISSUE TITLE
Connection reset

### ISSUE THREAD

**Issue by zlatkojosic** [stackmob/newman#124]
Hi,

I've use newman 1.3.5 in project. We have found lotof Connection reset errors:

java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(Unknown Source) ~[na:1.7.0_25]
        at java.net.SocketInputStream.read(Unknown Source) ~[na:1.7.0_25]
        at org.apache.http.impl.io.AbstractSessionInputBuffer.fillBuffer(AbstractSessionInputBuffer.java:166) ~[xpay.jar:0.1-SNAPSHOT]
        at org.apache.http.impl.io.SocketInputBuffer.fillBuffer(SocketInputBuffer.java:90) ~[xpay.jar:0.1-SNAPSHOT]

Thanks for any help.

Zlaja

**Comment by zlatkojosic** [comment]
Is it posible to use ApacheHttpClient from many threads? We use same instance from many thread implicit val httpClient = new ApacheHttpClient(socketTimeout = 40000, connectionTimeout = 40000).
